### ISSUE TITLE
[IMPROVE] Update pair view for new onboarding flow as per Figma

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1063]
**Is your feature request related to a problem? Please describe.**
For the new onboarding flow, the only view left to be updated is Pair.

**Tasks**
- [x] Update Pair view
- [x] Test it for Mac
- [x] Go through the onboarding process again to make sure that every single component matches the design on Figma.

**Figma Link**
https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=9327-20676&t=hsfH7QvAKgPa0jq3-4

**Screenshot**
<img width="807" alt="Screenshot 2024-08-20 at 2 39 05 PM" src="https://github.com/user-attachments/assets/f1772cbe-774f-4afb-90c6-c280141c47c1">

**Comment by realpaaao** [comment]
@Rockindash Please do not update this screen, keep it as it is in iOS. We will match it in figma. I personally like the iOS version more
